# Generated by Django 3.2.10 on 2023-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customername_customer_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='customerName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
