# Generated by Django 3.2.10 on 2023-01-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_rate_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rate_offer',
        ),
    ]
