# Generated by Django 3.2.10 on 2023-01-17 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('date_time_start', models.DateTimeField(default=datetime.datetime(2023, 1, 17, 9, 35, 19, 333696))),
                ('date_time_end', models.DateTimeField(default=datetime.datetime(2023, 1, 17, 9, 35, 19, 333696))),
                ('hours', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('task_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_hours', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('regular_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stat_holiday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floater', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('evening_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('evening_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weekend_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weekend_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vacation_pay_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ben_lieu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('task_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
