# Generated by Django 3.2.10 on 2023-02-26 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20230226_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='overtime',
            new_name='daily_overtime',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='overtime_pay',
            new_name='daily_overtime_pay',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_time_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 18, 19, 37, 516157)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_time_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 18, 19, 37, 516157)),
        ),
    ]
